drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

/*id 생략하고 insert해도 denerate해둬서 db가 알아서 추가해줌.*/
insert into member(name) values ('spring1');
insert into member(name) values ('spring2');

select * from member;